# Generated by Django 4.2.2 on 2023-06-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallary-image'),
        ),
    ]
