# Generated by Django 4.2.2 on 2023-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gallary_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
