# Generated by Django 4.2.2 on 2023-06-27 02:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_full_name_contact_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='carrier', unique=True),
        ),
    ]
