# Generated by Django 4.2.2 on 2023-06-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_hero_options_hero_created_at_hero_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
