# Generated by Django 4.2.2 on 2023-06-21 13:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
