# Generated by Django 4.2.2 on 2023-06-22 06:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('collage', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
